<?php

$apikey = $block->getAPIKey();
$customerSession = $block->getCustomerSession();

if ($customerSession->isLoggedIn()) {
    $customerId = $customerSession->getCustomerId();
    $customer = $customerSession->getCustomer();
    $displayName = $customer->getName();
    $email = $customer->getEmail();
    $joinDate = date('Y-m-d', strtotime($customer->getCreatedAt()));

    echo "<script>
            require(['jquery'], function ($) {
                window.GbLoadInit = function () {
                    GbSdk.init({
                        playerUniqueId: '$customerId',
                        playerAttributes: {
                            displayName: '$displayName',
                            email: '$email',
                            joinDate: '$joinDate'
                        },
                        lang: 'en',
                        APIKey: '$apikey'
                    });
                };
                document.addEventListener('readystatechange', event => {
                    if (event.target.readyState === 'complete') {
                        setTimeout(() => {
                            let script = document.createElement('script');
                            script.type = 'text/javascript';
                            script.src = 'https://assets.gameball.co/uat/widget/js/gameball-init.min.js';
                            script.defer = true;
                            document.getElementsByTagName('head')[0].appendChild(script);
                        }, 10000);
                    }
                });
            }
        );
    </script>";

} else {
    echo "<script>
        require(['jquery'], function ($) {
                window.GbLoadInit = function () {
                    GbSdk.init({
                        lang: 'en',
                        APIKey: '$apikey'
                    });
                };
                document.addEventListener('readystatechange', event => {
                    if (event.target.readyState === 'complete') {
                        setTimeout(() => {
                            let script = document.createElement('script');
                            script.type = 'text/javascript';
                            script.src = 'https://assets.gameball.co/uat/widget/js/gameball-init.min.js';
                            script.defer = true;
                            document.getElementsByTagName('head')[0].appendChild(script);
                        }, 10000);
                    }
                });
            }
        );
    </script>";

}

// echo "<script defer src='https://assets.gameball.co/uat/widget/js/gameball-init.min.js'></script>";
